services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

  server:
    image: asimmasood707/server:latest
    build: ./server
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynet
      
  client:
    image: asimmasood707/client:latest
    build: ./client
    ports:
      - "3000:80"
networks:
  mynet:  
    driver: bridge